name: build

on: [push, pull_request]

jobs:
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
        - name: macOS
          run: |
            brew install qt5 mosquitto curl-openssl zlib libuv sdl2 libpq sdl2_mixer
            mkdir build
            cd build
            cmake ..
            make -j 2
            ctest -V -C Debug -R tests-animation
            ctest -V -C Debug -R tests-computeshadertool
            ctest -V -C Debug -R tests-core
            ctest -V -C Debug -R tests-mail
            ctest -V -C Debug -R tests-math
            ctest -V -C Debug -R tests-util
            ctest -V -C Debug -R tests-stock
            ctest -V -C Debug -R tests-shadertool
            ctest -V -C Debug -R tests-testtraze
            ctest -V -C Debug -R tests-voxedit-util
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Linux
          run: |
            sudo apt-get update
            sudo apt-get install libglm-dev lua5.3 liblua5.3-dev libsdl2-dev postgresql-server-dev-10 libpq-dev libenet-dev libgtk-3-dev qt5-default qttools5-dev qttools5-dev-tools opencl-c-headers wayland-protocols pkg-config uuid-dev
            mkdir build
            cd build
            cmake ..
            make -j 2
            ctest -V -C Debug -R tests-animation
            ctest -V -C Debug -R tests-computeshadertool
            ctest -V -C Debug -R tests-core
            ctest -V -C Debug -R tests-mail
            ctest -V -C Debug -R tests-math
            ctest -V -C Debug -R tests-util
            ctest -V -C Debug -R tests-stock
            ctest -V -C Debug -R tests-shadertool
            ctest -V -C Debug -R tests-testtraze
            ctest -V -C Debug -R tests-voxedit-util
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: Windows
          run: |
            set VCPKG_DEFAULT_TRIPLET=x64-windows
            set VCPKG_BUILD_TYPE=release
            vcpkg install curl[winssl] libpq
            mkdir build
            cd build
            cmake .. -DRCON=OFF
            cmake --build .
            ctest -V -C Debug -R tests-animation
            ctest -V -C Debug -R tests-computeshadertool
            ctest -V -C Debug -R tests-core
            ctest -V -C Debug -R tests-mail
            ctest -V -C Debug -R tests-math
            ctest -V -C Debug -R tests-util
            ctest -V -C Debug -R tests-stock
            ctest -V -C Debug -R tests-shadertool
            ctest -V -C Debug -R tests-testtraze
            ctest -V -C Debug -R tests-voxedit-util
